### ISSUE TITLE
db.close => error : not a function

### ISSUE THREAD

**Issue by jmengelle** [mafintosh/mongojs#258] opened 2015-10-28 16:59 UTC
When i call db.close(), i got the error : 

TypeError: server.destroy is not a function
    at d:\[...]\node_modules\mongojs\lib\database.js:66:12

```javascript
Database.prototype.close = function (cb) {
  cb = cb || noop
  this._getServer(function (err, server) {
    if (err) return cb(err)
    server.destroy(true, true)
    cb()
  })
}
```

I use mongo 3.x and mongojs 1.4.1

**Comment by byleaf** [comment] 2015-11-20 12:51
+1

**Comment by aberenyi** [comment] 2015-11-23 13:51
+1

**Comment by saintedlama** [comment] 2015-12-02 09:22
Should be fixed in version 2.0 (released some seconds ago)

**Comment by saintedlama** [comment] 2015-12-02 09:37
Any feedback if this was fixed in 2.0 welcome. We could not really reproduce that behavior

**Comment by aberenyi** [comment] 2015-12-02 09:38
Nope, still does not work :(

**Comment by aberenyi** [comment] 2015-12-02 09:42
To reproduce, create a wrapper around mongojs
```js
function Mongo(connString, dbName)
{
  /**
   * Full connection string
   * @type {string}
   */
  this.connString = connString + '/' + dbName

  /**
   * Main mongo object
   */
  this.mongo = mongojs(this.connString, [], {authMechanism: 'ScramSHA1'})
  this.mongo.on('error', function(err)
  {
    return console.error(err)
  })

  /**
   * Close the connection
   */
  this.close = function()
  {
    this.mongo.close()
  }
}
```

And try to call it...
```js
var mongo = new Mongo(connString, 'db')
var collection = mongo.model('collection')
collection.find({}, function(err, docs)
{
  if (err) {callback(err, null)}
  //do something with the docs...

  //and now try to close the connection
  mongo.close()
})
```

It throws ```TypeError: server.destroy is not a function```.

HTH.

**Comment by saintedlama** [comment] 2015-12-02 09:53
@aberenyi this happens on mongojs version 2.0.0?

**Comment by aberenyi** [comment] 2015-12-02 09:56
Yeap, cannot reproduce?

**Comment by saintedlama** [comment] 2015-12-02 09:58
Could you provide me the call stack of the TypeError - I'm interested in which line of code in mongojs the issue arises and whether we can blame mongodb-native.

Could you also try to specify the auth mechanism in the connection URL like it's done here http://mongodb.github.io/node-mongodb-native/2.0/reference/connecting/authenticating/

**Comment by aberenyi** [comment] 2015-12-02 10:05
My bad. Forgot to uprev mongojs in the submodule. Works like a charm now. Thanks :beers:

**Comment by saintedlama** [comment] 2015-12-02 10:22
:tada: This issue was bugging us for quite some time :shipit:

**Comment by jmengelle** [comment] 2015-12-02 13:27
Changed to 2.0.0, no more error. 
Using mongo 3.0.x with ScramSHA1. 

And it seems that there is no more need to manually add the auth mechanism :)

unfortunately, we migrate a few days ago to 'mongodb' module.

**Closed** 2015-12-02 13:48 UTC
